version: 2
jobs:
  one:
    docker:
      - image: cimg/ruby:2.6.8
      auth:
        username: mydockerhub-user
        password: $DOCKERHUB_PASSWORD
        

    steps:
         - checkout
         - run: echo "A more familiar h1"
         - run: sleep 15
         
workflow:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
